name: Self hosted runner
on:
 push:

env:
  WF_ENV: Available to all jobs

jobs:
  execute_jobs:
    runs-on: [self-hosted]
    steps:
      - name: Log ENV vailables
        run: |
           echo "WF_ENV: ${WF_ENV}"
           echo "JOB_ENV: ${WF_ENV}"
           echo "STEP_ENV: ${WF_ENV}"
           echo 'execution completed. '
     - name: stop runner
       if: ${{ always() }}
       run: | 
          RUNNER_TOKEN="$(curl -XPOST -fsSL \
             -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/${SCOPE}/${_PATH}/actions/runners/registration-token" \
             | jq -r '.token')"
          ./config.sh remove --token $RUNNER_TOKEN
