name: Self hosted runner
on:
 push:

env:
  WF_ENV: Available to all jobs

jobs:
  execute_jobs:
    runs-on: [self-hosted]
    outputs:
      output1: ${{ steps.setuptoken.outputs.token }}
    steps:
     - name: codeBuildStep
       id: codeBuildStep 
       run: |
           echo "WF_ENV: ${WF_ENV}"
           echo "JOB_ENV: ${WF_ENV}"
           echo "STEP_ENV: ${WF_ENV}"
           echo 'execution completed. '
     - name: setuptoken
       id: setuptoken
       if: ${{ always() }}
       run: | 
          RUNNER_TOKEN="$(curl -XPOST -fsSL \
             -H "Authorization: token ${GITHUB_ACCESS_TOKEN}" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/${SCOPE}/${_PATH}/actions/runners/registration-token" \
             | jq -r '.token')"
           echo $RUNNER_TOKEN
           echo "::set-output name=token::$RUNNER_TOKEN"
  cleanup_jobs:
     runs-on: [self-hosted]
     needs: execute_jobs
     steps: 
      - name: Cleanup step
        run: |
           echo --------
           echo ${{needs.execute_jobs.outputs.output1}}
           echo --------
