name: ECS Runner Example
on:
 push:

jobs:
  execute_jobs:
    runs-on: [self-hosted]
    steps:
     - name: codeBuildStep
       id: codeBuildStep 
       run: |
           echo '-----------------------------------'
           echo 'PROJECT SPECIFIC BUILD STATEMENTS SHOULD BE IN THIS STEP'
           echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
           echo "GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}" 
           echo 'execution completed'
           echo '-----------------------------------'

           
