name: Self hosted runner
########
on:
 push:

env:
  WF_ENV: Available to all jobs

jobs:
  execute_jobs:
    needs: prepare_runner
    runs-on: [projectA]
    steps:
      - name: Log ENV vailables
        run: |
           echo "WF_ENV: ${WF_ENV}"
           echo "JOB_ENV: ${WF_ENV}"
           echo "STEP_ENV: ${WF_ENV}"
           echo 'execution completed. '    
